td_1 = "Overview"
td_1_1 = "Library Overview" 
url_1_1 = "Overview/_Body.htm"
td_1_2 = "License" 
url_1_2 = "Overview/License.htm"
td_1_3 = "Changes"
url_1_3 = "Overview/Changes.htm"
td_1_4 = "Example"
url_1_4 = "Overview/Example.htm"

td_2 = "Internet"
td_2_1 = "Clipper at SourceForge"
url_2_1 = "%http://sourceforge.net/projects/polyclipping/"
td_2_2 = "Clipper at angusj.com"
url_2_2 = "%http://www.angusj.com/delphi/clipper.php"
