// Configuration file to include everywhere
// one day should be generated by a configure script...
#ifndef CONFIG_H
#define CONFIG_H

#ifdef WIN32
#  define ENABLE_LUA    1
#endif

// turn on the license restricted gpc library for Shrink Nice
#define ENABLE_GPC 1

#endif
